version: '3.8'

services:
  web:
    container_name: ${CONTAINER_NAME:-pointvente-app-api}
    image: ${IMAGE_NAME:-pointvente-app-api}:latest
    build: .
    restart: unless-stopped
    environment:
      - SERVER_PORT=${SERVER_PORT:-8009}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:postgresql://pgsql.prod:5432/pointvente_db}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-89RQ7kaF7770Qy4343_t8hcjCfsqsKs}
    ports:
      - "${BIND_IP:-127.0.0.1}:${SERVER_PORT:-8009}:${SERVER_PORT:-8009}"
    networks:
      - apps.prod

networks:
  apps.prod:
    external: true

