version: '3.8'

services:
  web:
    container_name: saas-app-api
    image: saas-app-api:latest
    restart: unless-stopped
    environment:
      - SERVER_PORT=8010
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgsql.prod:5432/saas_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=89RQ7kaF7770Qy4343_t8hcjCfsqsKs
    ports:
      - "127.0.0.1:8010:8010"
    networks:
      - apps.prod

networks:
  apps.prod:
    external: true
