spring.application.name=pointvente

server.port=8009

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/pointvente_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Configuration pour �viter les probl�mes de LOB
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false





#security
jwt.secret=K9WJAYBWo2nsl7T0BtNiFEptw28PZDebaDMWqxhndpGPNe354j
jwt.expiration=3600

#Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Limites d'upload multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

