package com.gestion.persistent.model;

public enum GroupeArticle {
    CARRELAGE_SOL,
    CARRELAGE_MURAL,
    FAIENCE,
    MOSAIQUE,
    COSMETIQUE_MAQUILLAGE,
    COSMETIQUE_SOIN,
    COSMETIQUE_PARFUM,
    DROGUERIE_PEINTURE,
    DROGUERIE_OUTILLAGE,
    DROGUERIE_NETTOYAGE,
    EPI_PROTECTION,
    PRODUIT_GENERAL
}
